### ISSUE TITLE
Apk and license 

### ISSUE THREAD

**Issue by SamirSaidani** [iMADi-ARCH/quivr-mobile#1]
Is there an apk to try this? What is the license of the mobile app?

Thanks!

**Comment by adityanandanx** [comment]
No. This project has not been updated with the changes in quivr api and it does not work as of now. I don't have the time to continue working on this project.

**Comment by SamirSaidani** [comment]
Thanks for your answer, and all the work you've done 👍

If you are interested in devs continuing your work, it would be nice to set an opensource license. Your work would get a chance to live. 

I suggest MIT license.
